### ISSUE TITLE
Health check and postgres svc checks fail

### ISSUE THREAD

**Issue by afraser502** [redhat-developer/helm-backstage#19]
When installing this to a Vanilla Kubernetes cluster, the liveness checks never complete as they poll the http port, which never returns. Changing this from -  

```
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```
to this -
```
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
```

The secondary failure is the postgres service. 
```
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.database_port }}
      targetPort: http
      protocol: TCP
      name: http
```
results in postgres being unreachable.
Modifying to the postgres port resolves this.

Backstage pod log - 
```
[2m2022-11-14T11:19:12.366Z[22m [34mbackstage[39m [32minfo[39m Loaded config from app-config.yaml
[2m2022-11-14T11:19:12.397Z[22m [34mbackstage[39m [32minfo[39m 0 secret found in the config which will be redacted
[2m2022-11-14T11:19:12.425Z[22m [34mbackstage[39m [32minfo[39m Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: getaddrinfo ENOTFOUND backstage-postgresql.default.svc
    at /opt/app-root/src/node_modules/@backstage/backend-common/dist/index.cjs.js:1015:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CatalogBuilder.build (/opt/app-root/src/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4092:22)
    at async createPlugin$4 (/opt/app-root/src/packages/backend/dist/index.cjs.js:62:40)
    at async main (/opt/app-root/src/packages/backend/dist/index.cjs.js:206:29)
```

Backstage-postgres endpoint

```
NAME                                        ENDPOINTS                           AGE
backstage                                   x.x.x.x:7007                        10d
backstage-postgresql                        <none>                              10d
```
